#!/usr/bin/bash

readonly FILTER_PATH="/usr/local/share/libChangeLog/filter"

export CHANGE_LOG_TARGET="/tmp/$(basename $0).$$.tmp"
export CHANGE_LOG_IGNORE_PATTERN_PATH="$FILTER_PATH/$(basename $1).filter"

LD_PRELOAD=libChangeLog.so eval "$@"

if [ -e $CHANGE_LOG_TARGET ]
then
	cat $CHANGE_LOG_TARGET
	rm -f $CHANGE_LOG_TARGET
else
	false
fi
